"""Git hooks that run the project's verify commands without an agent (replaces the verify stage)."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import subprocess
import sys
from typing import Mapping, Sequence

from .atomic import atomic_write_many
from .configuration import resolve_effective_config
from .project import project_settings
from .team_init import active_hooks_dir

MARKER = "generated by gin-workflow hooks install"
HOOKS = ("pre-commit", "pre-push")
_PRE_COMMIT = ("lint", "typecheck")
_PRE_PUSH = {"easy": ("test",), "standard": ("test", "build"), "strict": ("test", "build", "e2e")}
_GIT_ENV = ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_PREFIX", "GIT_OBJECT_DIRECTORY", "GIT_COMMON_DIR")


def _shim(hook: str) -> str:
    return (f"#!/bin/sh\n# {MARKER}: {hook}\n"
            'command -v gin-workflow >/dev/null 2>&1 || '
            '{ echo "gin-workflow is not on PATH; run ./install.sh" >&2; exit 1; }\n'
            f'exec gin-workflow hooks run {hook} "$@"\n')


def install(root: Path) -> dict:
    active = active_hooks_dir(Path(root))
    if not active.is_dir():
        return {"status": "missing", "path": str(active), "hooks": {}}
    result: dict[str, str] = {}
    for hook in HOOKS:
        target, content = active / hook, _shim(hook)
        current = target.read_text(encoding="utf-8", errors="replace") if target.is_file() else None
        if current is not None and MARKER not in current:
            result[hook] = "occupied"
        elif current == content:
            result[hook] = "unchanged"
        else:
            atomic_write_many({target: content.encode("utf-8")}, mode=0o755)
            result[hook] = "installed"
    return {"status": "occupied" if "occupied" in result.values() else "installed",
            "path": str(active), "hooks": result}


def status(root: Path) -> dict[str, str]:
    active, out = active_hooks_dir(Path(root)), {}
    for hook in HOOKS:
        target = active / hook
        if not target.is_file():
            out[hook] = "missing"
        else:
            out[hook] = "ok" if MARKER in target.read_text(encoding="utf-8", errors="replace") else "occupied"
    return out


def _pushes_head(root: Path, refs: Sequence[str]) -> bool:
    """True when a pushed ref is a non-delete branch whose local sha is the checked-out HEAD."""
    head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root, text=True, capture_output=True,
                          check=False).stdout.strip()
    for line in refs:
        parts = line.split()
        if len(parts) == 4 and parts[0].startswith("refs/heads/") and parts[1] == head and set(parts[1]) != {"0"}:
            return True
    return False


def _run_commands(hook: str, commands: Sequence[tuple[str, str]], cwd: Path, env: Mapping[str, str]) -> int:
    for name, command in commands:
        print(f"gin-workflow {hook}: {name}: {command}", file=sys.stderr)
        code = subprocess.run(command, shell=True, cwd=cwd, env=dict(env)).returncode
        if code != 0:
            print(f"gin-workflow {hook}: {name} failed (exit {code})", file=sys.stderr)
            return code
    return 0


def run(root: Path, hook: str, refs: Sequence[str] = ()) -> int:
    root = Path(root)
    settings = project_settings(resolve_effective_config(root, write=False).config.to_dict())
    if hook == "pre-push":
        if not _pushes_head(root, refs):
            print("gin-workflow: pre-push tested nothing (no pushed branch at the checked-out HEAD)", file=sys.stderr)
            return 0
        names = _PRE_PUSH.get(settings.rigor, _PRE_PUSH["standard"])
    else:
        names = _PRE_COMMIT
    scoped = [(root, [(name, settings.verify_commands[name]) for name in names if settings.verify_commands.get(name)])]
    for package in settings.packages:
        checks = (package.get("verify") or {}).get("checks") or {}
        scoped.append((root / package["path"],
                       [(f"{package['path']}:{name}", checks[name]) for name in names if checks.get(name)]))
    if not any(commands for _, commands in scoped):
        print(f"gin-workflow: no verify commands configured for {hook}; nothing to run", file=sys.stderr)
        return 0
    env = {key: value for key, value in os.environ.items() if key not in _GIT_ENV}
    for cwd, commands in scoped:
        code = _run_commands(hook, commands, cwd, env)
        if code:
            return code
    return 0


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(prog="gin-workflow hooks")
    parser.add_argument("action", choices=("install", "run"))
    parser.add_argument("hook", nargs="?", choices=HOOKS)
    parser.add_argument("--repository", type=Path, default=Path.cwd())
    args = parser.parse_args(list(argv))
    root = args.repository.resolve()
    if args.action == "install":
        result = install(root)
        for hook, state in result["hooks"].items():
            print(f"{hook}: {state}")
        if result["status"] == "missing":
            print(f"hooks directory {result['path']} does not exist; create it or fix core.hooksPath", file=sys.stderr)
        if result["status"] == "occupied":
            print('add `exec gin-workflow hooks run <hook> "$@"` to the existing hook to chain it', file=sys.stderr)
        return {"installed": 0, "occupied": 1, "missing": 2}[result["status"]]
    if args.hook is None:
        parser.error("run needs a hook name")
    refs = sys.stdin.read().splitlines() if args.hook == "pre-push" and not sys.stdin.isatty() else []
    return run(root, args.hook, refs)
