"""`gin-workflow team init`: CODEOWNERS, PR/MR template, commit-msg hook, and optional CI per host."""

from __future__ import annotations

from pathlib import Path
import shutil
import subprocess
from typing import Any, Mapping

from .atomic import atomic_write_many
from .specs import render, sdd_config, template_text
from .team import TeamConfig

MARKER = "generated by gin-workflow team init"
_FILES = {
    "github": {"codeowners": ".github/CODEOWNERS", "template": ".github/pull_request_template.md",
               "ci": ".github/workflows/gin-workflow.yml", "ci_template": "team/github-ci.yml"},
    "gitlab": {"codeowners": ".gitlab/CODEOWNERS", "template": ".gitlab/merge_request_templates/Default.md",
               "ci": ".gitlab/ci/gin-workflow.yml", "ci_template": "team/gitlab-ci.yml"},
}
HOOK = ".githooks/commit-msg"


def codeowners_path(team: TeamConfig) -> str:
    return _FILES[team.host]["codeowners"]


def _logins(team: TeamConfig, roles: set[str]) -> list[str]:
    return sorted(f"@{member.login}" for member in team.members.values() if roles & set(member.roles))


def codeowners(team: TeamConfig, config: Mapping[str, Any]) -> str:
    """Area globs owned by the area lead; plan and spec folders owned by the approvers of those gates."""
    lines = [f"# {MARKER}; edit team: in .agent-workflow/config.yaml and rerun", ""]
    leads = {area.lead for area in team.areas.values()}
    for area in team.areas.values():
        owners = _logins(team, {area.lead})
        lines += [f"/{glob} {' '.join(owners)}" for glob in area.paths]
    artifacts = config.get("artifacts") if isinstance(config.get("artifacts"), Mapping) else {}
    cfg = sdd_config(config)
    spec_dirs = [cfg["specs"], cfg["changes"]] if cfg["layout"] == "sdd" else [".planning/specs"]
    requirement = team.approvals.get("requirement_confirmed", [])
    spec_roles = (set(requirement) if isinstance(requirement, list) else set()) | leads
    for directory, roles in ([(artifacts.get("plans", ".planning/plans"), leads)]
                             + [(directory, spec_roles) for directory in spec_dirs]):
        owners = _logins(team, roles)
        if owners:
            lines.append(f"/{str(directory).strip('/')}/ {' '.join(owners)}")
    return "\n".join(lines) + "\n"


def planned_files(root: Path, team: TeamConfig, config: Mapping[str, Any], *, ci: bool) -> dict[str, str]:
    names = _FILES[team.host]
    values = {"convention": team.commit_convention}
    files = {
        names["codeowners"]: codeowners(team, config),
        names["template"]: template_text(root, "team/pull_request_template.md"),
        HOOK: render(template_text(root, "team/commit-msg"), values),
    }
    if ci:
        files[names["ci"]] = render(template_text(root, names["ci_template"]), values)
    return files


def init(root: Path, team: TeamConfig, config: Mapping[str, Any], *, ci: bool = False,
         force: bool = False) -> dict[str, Any]:
    written, skipped, unchanged = [], [], []
    writes: dict[Path, bytes] = {}
    for relative, text in planned_files(root, team, config, ci=ci).items():
        path = Path(root) / relative
        if path.is_file():
            current = path.read_text(encoding="utf-8")
            if current == text:
                unchanged.append(relative)
                continue
            if MARKER not in current and not force:
                skipped.append(relative)
                continue
        writes[path] = text.encode("utf-8")
        written.append(relative)
    hook = Path(root) / HOOK
    if hook in writes:
        atomic_write_many({hook: writes.pop(hook)}, mode=0o755)
    if writes:
        atomic_write_many(writes, mode=0o644)
    return {"written": written, "skipped": skipped, "unchanged": unchanged}


def codeowners_drift(root: Path, team: TeamConfig, config: Mapping[str, Any]) -> bool:
    path = Path(root) / codeowners_path(team)
    return not path.is_file() or path.read_text(encoding="utf-8") != codeowners(team, config)


SHIM = f"""#!/bin/sh
# {MARKER}: commit-msg shim
exec "$(git rev-parse --show-toplevel)/{HOOK}" "$@"
"""


def active_hooks_dir(root: Path) -> Path:
    listed = subprocess.run(["git", "rev-parse", "--git-path", "hooks"], cwd=root, text=True, capture_output=True,
                            check=True).stdout.strip()
    return (Path(root) / listed).resolve()


def hook_active(root: Path) -> bool:
    active = active_hooks_dir(root)
    if active == (Path(root) / ".githooks").resolve():
        return (active / "commit-msg").is_file()
    path = active / "commit-msg"
    return path.is_file() and MARKER in path.read_text(encoding="utf-8", errors="replace")


def install_hook(root: Path) -> dict[str, Any]:
    """Point the active hooks directory (often `.beads/hooks`) at `.githooks/commit-msg` without changing it."""
    if not (Path(root) / HOOK).is_file():
        return {"status": "missing", "path": HOOK}
    active = active_hooks_dir(root)
    if active == (Path(root) / ".githooks").resolve():
        return {"status": "active", "path": HOOK}
    target = active / "commit-msg"
    if target.is_file() and MARKER not in target.read_text(encoding="utf-8", errors="replace"):
        return {"status": "occupied", "path": str(target)}
    active.mkdir(parents=True, exist_ok=True)
    atomic_write_many({target: SHIM.encode("utf-8")}, mode=0o755)
    return {"status": "installed", "path": str(target)}


def _ok(argv: list[str], root: Path) -> bool:
    if shutil.which(argv[0]) is None:
        return False
    try:
        return subprocess.run(argv, cwd=root, capture_output=True, check=False, timeout=30).returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def doctor_report(root: Path, team: TeamConfig, config: Mapping[str, Any]) -> dict[str, Any]:
    """`setup doctor` section for team mode: every check plus one fix per failing check."""
    from .team import current_member, has_policy

    cli = {"github": "gh", "gitlab": "glab"}[team.host]
    checks: dict[str, bool] = {
        "member": current_member(root, team) is not None,
        "host_cli": _ok([cli, "auth", "status"], root),
        "codeowners": not codeowners_drift(root, team, config),
    }
    if team.commit_convention != "none":
        checks["hook"] = hook_active(root)
    if has_policy("requirement_confirmed", team):
        checks["spec_review"] = sdd_config(config)["spec_review"] == "pr"
    if team.beads_remote:
        listed = subprocess.run(["bd", "dolt", "remote", "list"], cwd=root, text=True, capture_output=True,
                                check=False) if shutil.which("bd") else None
        checks["beads_remote"] = bool(listed and team.beads_remote in listed.stdout)
        if team.beads_remote.startswith("git+"):
            checks["beads_remote"] = checks["beads_remote"] and _ok(
                ["git", "ls-remote", "--heads", team.beads_remote[4:]], root)
    fixes = {
        "member": "add your git user.email to team.members, or fix `git config user.email`",
        "host_cli": f"install {cli} and run `{cli} auth login`",
        "codeowners": "run `gin-workflow team init` and commit the result",
        "hook": "run `gin-workflow team init` then `gin-workflow team hooks`",
        "spec_review": "set artifacts.spec_review: pr (requirement_confirmed needs PR approval)",
        "beads_remote": f"run `bd dolt remote add origin {team.beads_remote}` and `gin-workflow team sync`",
    }
    report: dict[str, Any] = {"checks": checks, "actions": [fixes[name] for name, ok in checks.items() if not ok]}
    if team.host == "gitlab":
        report["note"] = "GitLab Free cannot require code-owner approval; the gin-workflow check still applies"
    return report
