"""Production factory wiring the durable Track 1-3 data sources into one
:class:`CompositeEvidenceAuthority`.

Design note -- reference format and single global instance
------------------------------------------------------------
``CompositeEvidenceAuthority.resolve()`` (and therefore every resolver it
calls) only ever receives ``(category, reference)`` -- there is no task_id or
bead_id parameter available at resolve-call time (see
``workflow_providers.contracts.validate_authoritative_evidence``, which calls
``authority.resolve(evidence.category, evidence.reference)`` with nothing
else). ``ProviderRegistry`` also only builds one evidence authority per
process, shared across every task handled during that process's lifetime
(``FileEvidenceProvider`` itself is not task-scoped; task_id is threaded
per-call through ``EvidenceRecord``/``EvidenceQuery``). This factory matches
that existing single-authority-per-registry shape rather than constructing a
fresh authority per task.

Worker evidence references (``worker_id``) are already globally unique --
``worker_id_for()`` hashes ``(provider, workflow_id, task_id, retry_identity)``
-- so ``worker_resolver`` can scan the shared event store directly.

Review-ledger evidence references (``checkpoint_event_id`` /
``review_event_id``) are NOT globally unique: they are the ledger's own
sequential event ids (``EV-000001``, ``EV-000002``, ...), which collide across
every bead's ledger. Resolving one of those references therefore requires a
bead_id the resolver otherwise has no way to receive. To keep a single global
authority instance safe, checkpoint/review references consumed by this
factory's resolvers use the composite form ``"{bead_id}.{ledger_event_id}"``.
Callers that build ``EvidenceRecord`` instances for the repository/review
categories (and callers of ``record_verification`` for the matching
``review_event_id``) must use this same composite form so
``CompositeEvidenceAuthority``'s internal reference-equality checks
(``evidence.py``'s ``_checkpoint``/``_review``) succeed.

A ``:`` separator was considered and rejected: evidence.reference and the
matching ``details["checkpoint_event_id"]``/``details["review_event_id"]``
must both equal the composite string and both pass
``contracts._PORTABLE_EVIDENCE_ID`` (``^[A-Za-z0-9._-]+$``), which excludes
``:``. ``.`` is in that character set, but a bead_id CAN itself contain a
literal ``.`` (real examples exist in this repo's own Beads, e.g.
``gin-workflow-p80.8``), so splitting on the *first* ``.`` is wrong. Ledger
event ids are always the fixed, dot-free ``EV-{6 digits}`` form generated by
the ledger itself, so splitting on the *last* ``.`` (``str.rpartition``) is
unambiguous regardless of how many dots the bead_id contains.
"""

from __future__ import annotations

from pathlib import Path

from review_ledger.cli import get_checkpoint_identity_record, get_review_identity_record
from workflow_core.events import WorkflowEventStore
from workflow_core.models import thaw

from .evidence import (
    CompositeEvidenceAuthority,
    find_verification,
    find_verification_by_review,
)


def build_composite_evidence_authority(
    root: Path,
    event_store: WorkflowEventStore,
) -> CompositeEvidenceAuthority:
    """Wire Track 1-3's durable stores into one authoritative evidence resolver."""
    base_dir = str(root)

    def worker_resolver(reference: str):
        for event in event_store.read_all():
            if event.event_type != "worker.result":
                continue
            payload = event.payload
            if payload.get("worker_id") != reference:
                continue
            resolved = dict(thaw(payload))
            resolved["task_id"] = event.task_id
            resolved["recorded_at"] = event.timestamp
            return resolved
        return None

    def checkpoint_resolver(reference: str):
        bead_id, _, checkpoint_event_id = reference.rpartition(".")
        if not bead_id or not checkpoint_event_id:
            return None
        try:
            record = get_checkpoint_identity_record(
                bead_id, checkpoint_event_id, base_dir=base_dir
            )
        except FileNotFoundError:
            return None
        if record is None:
            return None
        return {**record, "checkpoint_event_id": reference}

    def review_resolver(reference: str):
        bead_id, _, review_event_id = reference.rpartition(".")
        if not bead_id or not review_event_id:
            return None
        try:
            record = get_review_identity_record(bead_id, review_event_id, base_dir=base_dir)
        except FileNotFoundError:
            return None
        if record is None:
            return None
        verification_event_id = find_verification_by_review(event_store, reference)
        if verification_event_id is None:
            return None
        return {
            **record,
            "review_event_id": reference,
            "verification_event_id": verification_event_id,
        }

    def verification_resolver(reference: str):
        return find_verification(event_store, reference)

    return CompositeEvidenceAuthority(
        worker_resolver=worker_resolver,
        checkpoint_resolver=checkpoint_resolver,
        review_resolver=review_resolver,
        verification_resolver=verification_resolver,
    )
