"""`gin-workflow team init`, CODEOWNERS drift, the commit-msg hook, and the hook shim."""

from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parent))

from team_fixtures import TEAM, fake_cli, git, make_team_repo, path_with, run_cli, write  # noqa: E402

GITHUB = [".github/CODEOWNERS", ".github/pull_request_template.md", ".githooks/commit-msg"]
GITLAB = [".gitlab/CODEOWNERS", ".gitlab/merge_request_templates/Default.md", ".githooks/commit-msg"]


class TestTeamInit(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.base = Path(self.tmp.name)

    def tearDown(self):
        self.tmp.cleanup()

    def test_github_files_rerun_and_codeowners(self):
        root = make_team_repo(self.base / "gh")
        result = run_cli(root, "team", "init")
        self.assertEqual(0, result.returncode, result.stderr)
        self.assertEqual([f"wrote {item}" for item in GITHUB], result.stdout.splitlines())
        self.assertEqual(0o755, (root / ".githooks/commit-msg").stat().st_mode & 0o777)
        self.assertEqual([f"unchanged {item}" for item in GITHUB], run_cli(root, "team", "init").stdout.splitlines())
        owners = (root / ".github/CODEOWNERS").read_text()
        for line in ("/services/** @binh-dev", "/tests/services/** @binh-dev", "/web/** @chi-fe",
                     "/.planning/plans/ @binh-dev @chi-fe", "/.planning/specs/ @an-ba @binh-dev @chi-fe"):
            self.assertIn(line + "\n", owners)
        self.assertEqual(0, run_cli(root, "team", "codeowners", "--check").returncode)

    def test_gitlab_files_and_ci(self):
        root = make_team_repo(self.base / "gl", host="gitlab")
        lines = run_cli(root, "team", "init", "--ci").stdout.splitlines()
        self.assertEqual([f"wrote {item}" for item in [*GITLAB, ".gitlab/ci/gin-workflow.yml"]], lines)
        self.assertIn('CONVENTION: "conventional"', (root / ".gitlab/ci/gin-workflow.yml").read_text())

    def test_github_ci_and_sdd_spec_owners(self):
        root = make_team_repo(self.base / "sdd", extra="artifacts:\n  layout: sdd\n")
        run_cli(root, "team", "init", "--ci")
        self.assertIn("'conventional' != 'none'", (root / ".github/workflows/gin-workflow.yml").read_text())
        owners = (root / ".github/CODEOWNERS").read_text()
        self.assertIn("/docs/specs/ @an-ba @binh-dev @chi-fe\n", owners)
        self.assertIn("/docs/changes/ @an-ba @binh-dev @chi-fe\n", owners)

    def test_user_owned_file_is_skipped_unless_forced(self):
        root = make_team_repo(self.base / "own")
        write(root, ".github/pull_request_template.md", "our own template\n")
        lines = run_cli(root, "team", "init").stdout.splitlines()
        self.assertIn("skipped .github/pull_request_template.md (no marker; --force overwrites)", lines)
        self.assertEqual("our own template\n", (root / ".github/pull_request_template.md").read_text())
        run_cli(root, "team", "init", "--force")
        self.assertIn("generated by gin-workflow", (root / ".github/pull_request_template.md").read_text())

    def test_codeowners_check_detects_drift(self):
        root = make_team_repo(self.base / "drift")
        self.assertEqual(1, run_cli(root, "team", "codeowners", "--check").returncode)
        run_cli(root, "team", "init")
        config = root / ".agent-workflow/config.yaml"
        config.write_text(config.read_text().replace("login: chi-fe", "login: chi-new"))
        result = run_cli(root, "team", "codeowners", "--check")
        self.assertEqual(1, result.returncode)
        self.assertIn(".github/CODEOWNERS is out of date", result.stdout)


class TestCommitMsgHook(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.base = Path(self.tmp.name)

    def tearDown(self):
        self.tmp.cleanup()

    def hook(self, root: Path, subject: str) -> int:
        message = self.base / "MSG"
        message.write_text(f"# comment\n{subject}\n\nbody\n")
        return subprocess.run([str(root / ".githooks/commit-msg"), str(message)], capture_output=True).returncode

    def test_conventional_subjects(self):
        root = make_team_repo(self.base / "c")
        run_cli(root, "team", "init")
        for subject in ("feat: add login", "fix(api)!: drop v1", "chore(deps): bump", "Merge branch 'x'",
                        "fixup! feat: add login", 'Revert "feat: add login"'):
            with self.subTest(subject):
                self.assertEqual(0, self.hook(root, subject))
        for subject in ("add login", "feature: add login", "feat:", "Feat: add"):
            with self.subTest(subject):
                self.assertEqual(1, self.hook(root, subject))

    def test_none_convention_accepts_anything(self):
        root = make_team_repo(self.base / "n", team=TEAM.format(host="github").replace(
            "team:\n", "team:\n  commit_convention: none\n"))
        run_cli(root, "team", "init")
        self.assertEqual(0, self.hook(root, "whatever"))

    def test_shim_in_active_hooks_dir(self):
        root = make_team_repo(self.base / "s")
        self.assertEqual(2, run_cli(root, "team", "hooks").returncode)
        run_cli(root, "team", "init")
        git(root, "config", "core.hooksPath", ".beads/hooks")
        installed = run_cli(root, "team", "hooks")
        self.assertEqual(0, installed.returncode, installed.stderr)
        self.assertTrue(installed.stdout.startswith("installed: "))
        git(root, "add", "-A")
        bad = subprocess.run(["git", "commit", "-q", "-m", "no convention"], cwd=root, capture_output=True, text=True)
        self.assertNotEqual(0, bad.returncode)
        self.assertIn("Conventional Commits", bad.stderr)
        good = subprocess.run(["git", "commit", "-q", "-m", "chore: init"], cwd=root, capture_output=True, text=True,
                              env={**os.environ})
        self.assertEqual(0, good.returncode, good.stderr)
        write(root, ".beads/hooks/commit-msg", "#!/bin/sh\nexit 0\n")
        self.assertEqual(1, run_cli(root, "team", "hooks").returncode)
        git(root, "config", "core.hooksPath", ".githooks")
        self.assertTrue(run_cli(root, "team", "hooks").stdout.startswith("active: "))


if __name__ == "__main__":
    unittest.main()


class TestTeamDoctor(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.base = Path(self.tmp.name)
        self.bin = self.base / "bin"

    def tearDown(self):
        self.tmp.cleanup()

    def doctor(self, root: Path) -> dict:
        result = run_cli(root, "setup", "doctor", "--format", "json", env=path_with(self.bin))
        return json.loads(result.stdout)

    def test_team_section_reports_each_fix_until_healthy(self):
        root = make_team_repo(self.base / "d", extra="artifacts:\n  spec_review: pr\n")
        fake_cli(self.bin, "gh", [{"argv": ["auth", "status"], "stdout": "ok"}])
        payload = self.doctor(root)
        self.assertEqual({"member": True, "host_cli": True, "codeowners": False, "hook": False, "spec_review": True},
                         payload["checks_details"]["team"]["checks"])
        self.assertEqual(["team: run `gin-workflow team init` and commit the result",
                          "team: run `gin-workflow team init` then `gin-workflow team hooks`"],
                         [a for a in payload["actions"] if a.startswith("team:")])
        self.assertFalse(payload["checks"]["team"])
        run_cli(root, "team", "init")
        run_cli(root, "team", "hooks")
        payload = self.doctor(root)
        self.assertTrue(payload["checks"]["team"], payload["checks_details"]["team"])

    def test_spec_review_chat_and_gitlab_note(self):
        root = make_team_repo(self.base / "g", host="gitlab")
        fake_cli(self.bin, "glab", [{"argv": ["auth", "status"], "exit": 1}])
        detail = self.doctor(root)["checks_details"]["team"]
        self.assertFalse(detail["checks"]["spec_review"])
        self.assertFalse(detail["checks"]["host_cli"])
        self.assertIn("GitLab Free", detail["note"])

    def test_no_team_section_without_team_block(self):
        root = make_team_repo(self.base / "solo", team="")
        payload = self.doctor(root)
        self.assertNotIn("team", payload["checks_details"])
        self.assertNotIn("team", payload["checks"])
